### ISSUE TITLE
How to validate that a prop implements a certain typescript interface

### ISSUE THREAD

**Issue by paulvanbladel** [kaorun343/vue-property-decorator#14]
Imagine I have following typescript vue  component class
```
export default class MyClass extends Vue {

  @Prop
  MyCollection: MyModel[];
```
It seems not to be the case that the incoming type MyModel[] is validated.

What do you suggest to get this working? Could a custom validator help?
Thanks.

**Comment by dkapellusch** [comment]
You can put the component decorator which specifies the props and their types on that class. It doesn't provide compile time checking, but at runtime you will get a debug warning that the types do not line up. For instance if you define your component class like this:
`@Component({
    props:{
        propMessage:String
    }
})
export default class App extends Vue  {
    @Prop
    propMessage : string;`
}

Then if you try to call it like:
`let myProps :ComponentOptions<Vue> = {
    propsData:{
        propMessage:12
    }
}
new App({...myProps}).$mount("#app");`

It will render fine, but in the debug console you will see a message like "[Vue warn]: Invalid prop: type check failed for prop "propMessage". Expected String, got Number. 
(found in <Root>)".

If you want to get compile time checking I got around it by defining my own version of ComponentOptions<T,Vue> where T is an interface representing the props for the component.

**Comment by kaorun343** [comment]
@paulvanbladel 

Hi.

In my humble opinion, It's better to check by `validator` option rather than `instanceof` checking.
It's because when using Vue's devtools, when changing Vuex's state by it, and when checking prop values by `instanceof`, we'll give a message `Invalid prop`. Internally, devtools are doing deep clone, so `instanceof` will throw `false`.

Therefore, I recommend you to do like this below.

```ts
// If your MyModel is like this
class MyModel {
  name: string
  age: number
}

@Component
class MyClass extends Vue {
  @Prop({
    validator: items => items.all(i => typeof i.name === 'string' && typeof i.age === 'number')
  })
  MyCollection: MyModel[]
```

Or, if `MyClass` has many child components that passed an item of `MyCollection`, type checking should be done in those children, I think. 

However, I understand this way isn't cool.
As @dkapellusch wrote, there're needed to be a change in a typescript field.

**Comment by paulvanbladel** [comment]
@kaorun343 @dkapellusch 
Thank you very much for your suggestions. Highly appreciated. I'll start experimenting with your input.
I wish you a great day.
