### ISSUE TITLE
Class component is using reflect metadata now

### ISSUE THREAD

**Issue by HIMISOCOOL** [kaorun343/vue-property-decorator#149]
the older version had automatic type inference in @Prop but these features were removed due to reflect-metadata being spotty.
vue-class-component just added it as a dependency to 6.3.0 does this open the door to re-adding this feature?

**Comment by kaorun343** [comment]
@HIMISOCOOL 

Hi.

I know `vue-class-component` added `reflect-metadata`, but I won’t use it again because `@Component` decorator just supports using metadata and works well without the package.

Inferring props’ types works only in development build. Also, some developers mentioned the problems related to infer the types by the package. I decided to remove the package from this library due to these reasons.
