### ISSUE TITLE
Problem with default inside @Prop()

### ISSUE THREAD

**Issue by mailok** [kaorun343/vue-property-decorator#160]
Hi!, i am use Vuejs with typescript, and i have a props that is a Funtion:
This code dont work;
``` 
@Prop({ default: () => console.log('settings....') }) setting: Function;
```

For it to work, I had to put the type of data inside a body:
```
  @Prop({
        type: Function,
        default: () => console.log('settings....')
    })
    setting: Function; 
```

Is that something that you forgot to comment in the Readme or is it a Bug?
If I do not put the type of data in the body Vuejs gives error:
```
[Vue warn]: Invalid handler for event "click": got undefined 
```

My template is: 
```
 <v-btn flat block @click="setting">Configuración</v-btn>
```

**Comment by foxbunny** [comment]
In this case, I believe it's the *return value* that is used as the default. You would need to write `() => () => console.log(...)`.

**Comment by mailok** [comment]
@foxbunny  That works!!! But I do not understand why

**Comment by foxbunny** [comment]
It's a Vue feature. If you pass a function as a default, it will call the function and use the return value as the default value. This is useful for mutable data structures like objects and arrays where you don't want the mutate the default value. Because functions are reserved for this, you have to return a function in order to have a default value that is a function.
