### ISSUE TITLE
correct way to use @Prop with my own type?

### ISSUE THREAD

**Issue by damonus-prime** [kaorun343/vue-property-decorator#236]
`import { Person } from '@/types';

@Component({

})
export default class PersonManager {
// this does NOT work.  What's the correct way?
@Prop(Person) private readonly dude: Person;
}
`

I get this error:

'Person' only refers to a type, but is being used as a value here.

Person is declared as an interface, if that helps.

TIA

**Comment by asbermudez** [comment]
@damonus-prime You need to understand what is doing under the hood. The `type` on the props from Vue is a runtime check based on normal javascript comparation of `typeof`, because of the same very nature of Typescript (it's just used BEFORE transpiling) you cannot do typescript checks in runtime.
So basically the Type property of the Props in VueJS only accepts native types of objects (like String, Object, Function...). Not even classes, as the classes are syntactic sugar and they really turn into something else.

Hope it helped!

You can check documentation about this in the official site of VueJS:
https://vuejs.org/v2/guide/components-props.html#Type-Checks

**Comment by asbermudez** [comment]
You might be able to do this:
https://github.com/kaorun343/vue-property-decorator#if-youd-like-to-set-type-property-of-each-prop-value-from-its-type-definition-you-can-use-reflect-metadata

**Comment by ordsen** [comment]
I know this tread is a bit old, but maybe this helps others who have this question:

```
import { PropType } from 'vue';
import { Component, Vue, Prop } from 'vue-property-decorator';

import { Person } from '@/yourtypes';

@Component
export default class PersonManager extends Vue {
  @Prop({
    type: Object as PropType<Person>,
  }) person: Person;
}
```

**Comment by kaorun343** [comment]
Please set `Object` to type explicitly, if a prop is typed by interface or type alias.
