### ISSUE TITLE
How to set default prop value with object or function?

### ISSUE THREAD

**Issue by zhouxinyong** [kaorun343/vue-property-decorator#253]
I use @prop to define default value with object of function like this:
```
@Prop({ default: () => {} }) options!: any
@Prop({ default: () => {} }) callback!: Function
```
then in vue DevTools i find this:
![image](https://user-images.githubusercontent.com/15569753/63834488-fd6cd400-c9a7-11e9-8e4b-5e11f593e233.png)

when I change my code to this:
```
@Prop({ default: () => ({}) }) options!: any
@Prop({ default: () => () => {} }) callback!: Function
```
then in vue DevTools i find it get correct:
![image](https://user-images.githubusercontent.com/15569753/63834604-44f36000-c9a8-11e9-817c-bf33c5ab13ae.png)

The second way of writing is really weird.So,what is the right way to set default prop value with object or function?

**Comment by nnabinh** [comment]
I have the same issue too. Anyone?

**Comment by zhouxinyong** [comment]
@nnabinh I try this,but it's not work.
The options return  `ƒ _default() {}` in vue DevTools.

**Comment by jonnyparris** [comment]
@zhouxinyong see here for an answer: https://github.com/kaorun343/vue-property-decorator/issues/160

**Comment by PhilippMeissner** [comment]
I might be late to the party but maybe it's still worth a shot:

```
@Prop({ default: () => {} }) options!: any
```

The reason the prop is showing up as `undefined` seems to be that `() => {}` is equivalent to `() => {return};` (so `{}` gets interpreted as empty function body).

In order to assign it an empty object, you'd have to cover the return value in `()` like so
```
@Prop({ default: () => ({}) }) options!: any
```

Hope that may be of help to somebody.
