### ISSUE TITLE
Configuring vue-router navigation guards

### ISSUE THREAD

**Issue by larvanitis** [kaorun343/vue-property-decorator#259]
If I setup some custom hooks for the vue-router on `Component` imported from `vue-class-component`, they don't later work in components annotated with `@Component` imported from `vue-property-decorator`.

Note, I am new to Vue and I use the Quasar framework with quasar-cli. It uses/loads the `boot/*` files "inside" `main.js`, and `Component.registerHooks()` is definitelly called before `new Vue()`.

So:
```typescript
// boot/vue-typescript-setup.ts
import {Component} from 'vue-property-decorator';
Component.registerHooks([...]);

// pages/MyPageProp.vue - WORKS
import {Component} from 'vue-property-decorator';
@Component
...

// pages/MyPageClass.vue - WORKS
import Component from 'vue-class-component';
@Component
...
```

 while:
```typescript
// boot/vue-typescript-setup.ts
import Component from 'vue-class-component'; // only difference
Component.registerHooks([...]);

// pages/MyPageProp.vue - DOES NOT WORK
import {Component} from 'vue-property-decorator';
@Component
...

// pages/MyPageClass.vue - WORKS
import Component from 'vue-class-component';
@Component
...
```

Related? #42 #38

**Comment by neoye911** [comment]
@larvanitis encountered same issue as you, Component.registerHooks() before importing other components, but still couldn't use the beforeRouteUpdate() hook.

**Comment by adamJLev** [comment]
I am having the same issue.

The reason is that `vue-property-decorator` installs its own version of `vue-class-component` so even if you register early, its not registering it on the same instance of the `Component` class: https://github.com/kaorun343/vue-property-decorator/blob/master/package.json#L36

@kaorun343  I think maybe  easiest fix is to make `vue-class-component` a peer dependency here so that it actually uses the same instance as would be imported from `vue-class-component`?

For the rest of us, here's a workaround for now though:

```typescript
import {Component as C1} from 'vue-property-decorator';
import C2 from 'vue-class-component'

C1.registerHooks([
  'beforeRouteEnter',
  'beforeRouteLeave',
  'beforeRouteUpdate'
])

C2.registerHooks([
  'beforeRouteEnter',
  'beforeRouteLeave',
  'beforeRouteUpdate'
])
```

**Comment by jiang263** [comment]
how to resolve it？

**Comment by pribilinskiy** [comment]
Same here, @adamJLev's workaround didn't help

**Comment by kaorun343** [comment]
This issue seems to be fixed by moving `vue-class-component` to peerDependencies.
