### ISSUE TITLE
can‘t get this.$options.data()

### ISSUE THREAD

**Issue by 1045598742** [kaorun343/vue-property-decorator#343]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kaorun343** [comment]
@1045598742 Could you provide any reproduction code?

**Comment by raohuiyong** [comment]
我也遇到这个问题
this.$options.data()类型检查报错
![image](https://user-images.githubusercontent.com/26049430/105976684-72779800-60cb-11eb-8163-39853560b92a.png)

this.$options.data打印结果![image](https://user-images.githubusercontent.com/26049430/105976481-30e6ed00-60cb-11eb-97d7-3c9a86c1eccc.png)

vue-property-decorator 9.1.2
vue-class-component 7.2.6
vue 2.6.11

**Comment by kaorun343** [comment]
@raohuiyong 
This is caused by Vue's type definition. `this.$options.data` is possibly `undefined`, as you know, sometimes `data` option is `undefined` . This is not a bug. So, to solve this problem, you can use  [Non-null assertion operator](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator) . Please read this TypeScript document. Thanks.

**Comment by raohuiyong** [comment]
![image](https://user-images.githubusercontent.com/26049430/112422696-3af43780-8d6c-11eb-801b-6c51d3532eb0.png)


上面一段代码打印出来，返回一个空对象{}，并没有返回一个初始化的设置

**Comment by gdoudeng** [comment]
@raohuiyong 老哥解决了吗

**Comment by raohuiyong** [comment]
> @raohuiyong 老哥解决了吗
没有解决
