### ISSUE TITLE
@Emit decorator emits the object duplicated

### ISSUE THREAD

**Issue by CarlosGuedesPinto** [kaorun343/vue-property-decorator#406]
**Describe the bug**
I'm using the `@Emit` decorator in TS, and somehow, on my tests, I'm receiving the emit object duplicated, when returning.

**To Reproduce**
1. Create emit and return the params received
2. Check on the tests what is emitted

**Expected behavior**
It should only send one instance of the emit, not two of them (duplicated).

**Screenshots**
![image](https://user-images.githubusercontent.com/25008836/138861551-6e175ff9-d093-4ece-9b08-2f9da306cb90.png)
![image](https://user-images.githubusercontent.com/25008836/138861636-282f68ee-fa9b-4479-9671-e3bafb634add.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome

**Additional context**
With the non-decorator way of emits, I receive the emit as it should.
![image](https://user-images.githubusercontent.com/25008836/138861977-241ccbb5-5ef0-4805-bcf6-07ceeebe71ce.png)
![image](https://user-images.githubusercontent.com/25008836/138862020-c62a487e-a4d7-46d6-b98c-68af13c9b6e4.png)

**Comment by alecgibson** [comment]
I just ran into this. The issue is [here](https://github.com/kaorun343/vue-property-decorator/blob/e04872349bab357e6d08b01442f83abc9976eb50/src/decorators/Emit.ts#L29-L30), where the return value is combined with the args for the function and it's all emitted together. This is fine for listeners (which can just ignore later arguments), but is surprising in tests.

One potential fix is that if you have code that does this:

```ts
@Emit('event')
public emitEvent(value: string): string {
  return string;
}
```

You can change it to this:

```ts
@Emit('event')
public emitEvent(_value: string): void {}
```

But beware, this *won't* work when moving to `vue-facing-decorator`, which just [emits the return value](https://github.com/facing-dev/vue-facing-decorator/blob/ea951fde01cfa3bc769d6a33311f99a2476bcb19/src/option/emit.ts#L32).
