### ISSUE TITLE
Problem with @model and vue-warrning

### ISSUE THREAD

**Issue by kamil-kielczewski** [kaorun343/vue-property-decorator#70]
Template for HomePage:
`<div>Write something: <input v-model="someName" type="text"> </div>`

TypeScript:

```
import { Component, Emit, Inject, Model, Vue } from "vue-property-decorator";

@Component
export default class HomePage extends Vue {
    @Model('change') someName: string;
}
```

After compilation, run in browser and type something on input box i get in chrome console following vue warrning:

> Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: someName

Any idea how to fix this problem?

**Comment by frankier** [comment]
I have the same problem. It didn't happen in 5.1.1, but it happens with 6.0.0 so I guess it's been introduced at some point between these two versions.

**Comment by frankier** [comment]
Okay, no. I seem to have a different problem that only occurs when the model attribute is initialised from a prop.

**Comment by frankier** [comment]
Okay, it also happens when it's initialised with a literal. Sending a PR.

**Comment by frankier** [comment]
Hrm but this breaks uninitialised attributes. It seems that now @model attributes need to be initialised using {default: xxx} and initialising from a prop is not longer supported.

**Comment by frankier** [comment]
In fact, it seems I have completely misunderstood the purpose of @Model . I understand now that it's for *exposing* stuff from your component via v-model rather than for data attributes within your component which are set by child v-model attributes. It seems I'm not the only one to misunderstand this. See: https://github.com/kaorun343/vue-property-decorator/issues/84 . While this is to some extent a misunderstanding of Vue, perhaps it could be flagged up here since it might be a common tripping point?

**Comment by kamil-kielczewski** [comment]
@frankier here is answer: https://stackoverflow.com/q/47607338/860099

**Comment by frankier** [comment]
Yes, that will also fix it, but there's no evidence from your question that you actually need `provide' and not just an unannotated `data' attribute.

**Comment by RehanSaeed** [comment]
Am I correct in thinking that to use `v-model` the correct method is to setup an `@Model` property with a string passed in that determines the event name like so:

```
  @Model("input", {
    default: moment()
  })
  public value!: string;
```

Then to actually emit the event, to use `@Emit` with the same event name as above.

```
  @Emit("input")
  public onValueChanged(value: string) {
    this.value = value;
  }
```

Finally, when you want to change the value from within the component you need to call the event emitter function:

```
onValueChanged("Foo Bar")
```

**Comment by tryforceful** [comment]
@RehanSaeed Something like this... though I believe your `onValueChanged` function needs to return the new value in order for the `@Emit` decorator to propagate it upwards via an emit event.

I find this `@Model` decorator misleading/confusing, to be honest... And I don't necessarily agree that `@Provide` should be used in order to make @kamil-kielczewski's use case work
